### ISSUE TITLE
Fix issues with the package

### ISSUE THREAD

**Issue by IgorSasovets** [webdriverio-community/wdio-geckodriver-service#6]
Hello team!

After an upgrade to the _wdio-geckodriver-service_ v2.0.0 I noticed that every time when you want to launch your e2e test suites on Firefox browser _@wdio/sync_ throws the following error into a console:
```
0-0] 2021-05-26T15:23:32.683Z INFO geckodriver: Start Geckodriver (/home/user/wdio-project/node_modules/geckodriver/geckodriver) with args: --log=info --port=34177
[0-0] 2021-05-26T15:23:32.743Z ERROR @wdio/sync: ReferenceError: split2 is not defined
    at GeckoService._startDriver (/home/user/wdio-project/node_modules/wdio-geckodriver-service/src/index.js:128:33)
```

I think that it happens because the _split2_ package is not imported in [index.js](https://github.com/webdriverio-community/wdio-geckodriver-service/blob/main/src/index.js). Could you please take a look at this? 
It can be fixed by adding the following LOC at the beginning of [index.js](https://github.com/webdriverio-community/wdio-geckodriver-service/blob/main/src/index.js):
```
const split2 = require('split2');
```
I tested it on my local machine and it helped me to resolve the issue.

Unfortunately, it wasn't the last issue within the [index.js](https://github.com/webdriverio-community/wdio-geckodriver-service/blob/main/src/index.js) file. When I launched my e2e test suite once again I got the following error from _@wdio/sync_ in logs:

```
[0-0] 2021-05-26T15:39:29.610Z INFO geckodriver: Start Geckodriver (/home/user/wdio-project/node_modules/geckodriver/geckodriver) with args: --log=info --port=41137
[0-0] 2021-05-26T15:39:29.641Z INFO geckodriver: 1622043569638	geckodriver	INFO	Listening on 127.0.0.1:41137
[0-0] 2021-05-26T15:39:29.650Z ERROR @wdio/sync: TypeError: Cannot read property 'bind' of undefined
    at GeckoService._startDriver (/home/user/wdio-project/node_modules/wdio-geckodriver-service/src/index.js:133:44)
```

It would be nice if you take a look at the aforementioned issues.

Best regards,
Ihor

**Comment by christian-bromann** [comment]
Thanks for reporting @IgorSasovets , the issue has been fixed and released as `v2.0.1`.
